create extension if not exists "uuid-ossp";
create table if not exists mya_contacts (id uuid primary key default uuid_generate_v4(), phone text not null unique, name text, email text, company text, address text, project_type text, lead_source text, status text default 'new', notes text, last_call_summary text, total_calls integer default 0, last_contact_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create index if not exists idx_mya_contacts_phone on mya_contacts(phone);
create table if not exists mya_conversations (id uuid primary key default uuid_generate_v4(), conversation_id text unique, contact_id uuid references mya_contacts(id), phone text, direction text default 'inbound', duration_secs integer default 0, summary text, transcript jsonb, call_successful text, started_at timestamptz, created_at timestamptz default now());
create index if not exists idx_mya_conversations_phone on mya_conversations(phone);
create table if not exists mya_actions (id uuid primary key default uuid_generate_v4(), type text not null, status text default 'pending', payload jsonb, error text, executed_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create index if not exists idx_mya_actions_status on mya_actions(status, created_at asc);
create table if not exists mya_intakes (id uuid primary key default uuid_generate_v4(), full_name text, phone text, email text, property_address text, city text, state text, zip text, company_name text, project_type text, project_scale text, motivation text, project_description text, timeline text, budget_range text, decision_makers text, contractor_history text, lead_source text, call_disposition text, follow_up_date date, notes text, red_flags text, status text default 'new', qualified_by text default 'mya', created_at timestamptz default now());
create table if not exists mya_notifications (id uuid primary key default uuid_generate_v4(), type text, severity text default 'info', title text, message text, metadata jsonb, read boolean default false, created_at timestamptz default now());
create index if not exists idx_mya_notifications_created on mya_notifications(created_at desc);
create table if not exists mya_memory (id uuid primary key default uuid_generate_v4(), key text not null unique, value jsonb, updated_at timestamptz default now());
alter table mya_contacts enable row level security;
alter table mya_conversations enable row level security;
alter table mya_actions enable row level security;
alter table mya_intakes enable row level security;
alter table mya_notifications enable row level security;
alter table mya_memory enable row level security;
create policy "service_all" on mya_contacts for all using (true);
create policy "service_all" on mya_conversations for all using (true);
create policy "service_all" on mya_actions for all using (true);
create policy "service_all" on mya_intakes for all using (true);
create policy "service_all" on mya_notifications for all using (true);
create policy "service_all" on mya_memory for all using (true);